<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CodexLinxDisplay.Core\CodexLinxDisplay.Core.csproj" />
    <ProjectReference Include="..\..\src\CodexLinxDisplay.Rendering\CodexLinxDisplay.Rendering.csproj" />
  </ItemGroup>
</Project>
